SELECT * FROM customer LIMIT 5;

--1) What is the total revenue generated by male vs female customers

SELECT 
    gender,
    SUM(purchased_amount) as revenue
FROM customer
GROUP BY gender;

--2) Which customers used a discount but still spent more than the average purchase amount?

SELECT
    customer_id,
    purchased_amount
FROM customer
WHERE discount_applied = 'Yes' 
AND purchased_amount >= (SELECT AVG(purchased_amount) FROM customer);

--3) Which are the top 5 products with the highest average review rating?

SELECT
    item_purchased,
    ROUND(AVG(review_rating::NUMERIC),2) avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--4) Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT
    shipping_type,
    ROUND(AVG(purchased_amount),2)
FROM customer
WHERE shipping_type IN('Standard','Express')
GROUP BY shipping_type;

--5) Do subscribed customers spend more? Compare average spend and total revenue
--   between subscribers and non subscribers.

SELECT 
    subscription_status,
    COUNT( customer_id) as total_customers,
    round(AVG(purchased_amount),2) avg_spend,
    Round(sum(purchased_amount),2) total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--6) Which 5 products have the highest percentage of purchases with discount applied?

SELECT
    item_purchased,
    ROUND(100 *SUM(CASE
        WHEN discount_applied = 'Yes' THEN 1
        ELSE 0
        END)/count(*),2) discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--*7) Segment customers into new, returning and Loyal based on their total
--    number of previous purchases, and show the count of each segment.

WITH Customer_type AS(
SELECT 
    customer_id,
    previous_purchases,
    CASE
        WHEN previous_purchases =1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM customer)

SELECT 
    customer_segment,
    COUNT(*) AS "Number of customers"
    FROM Customer_type
    GROUP BY customer_segment;

--8) What are the top 3 most purchased product in each category?
---using CTE
WITH item_counts AS(
SELECT
    category,
    item_purchased,
    COUNT(customer_id) total_orders,
    Row_Number() OVER(PARTITION BY category 
                      ORDER BY COUNT(customer_id) DESC) item_rank
FROM customer
GROUP BY category,item_purchased)

SELECT
    category,
    item_purchased,
    total_orders,
    item_rank
FROM item_counts
WHERE item_rank <=3;

--*9) Are customers who are repeat buyers (more than 5 previous purchased)
--   also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--10) What is the revenue contribution of each age group

SELECT 
    age_group,
    sum(purchased_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
